name: 'Interface exporter action'
description: 'An action to generate npm packages based on Solidity contract interfaces'
author: 'Wonderland'
inputs:
  out_dir:
    description: 'path to the `out` folder containing the compiled contracts'
    required: true
  interfaces_dir:
    description: 'path to the `interfaces` folder containing the contract interfaces'
    default: 'src/interfaces'
    required: false
  typing_type:
    description: 'interface compatibility: abi, ethers-v6, web3-v1'
    required: true
  package_name:
    description: 'name of the package to be publish'
    required: true
  destination_dir:
    description: 'path to the directory where your package will be exported'
    required: true
outputs:
  passed:
    description: 'boolean describing if the test passed or not'
runs:
  using: node20
  main: 'dist/index.js'
