name: 'Solidity exporter action'
description: 'An action to generate npm packages based on Solidity interfaces and contracts'
author: 'Wonderland'

inputs:
  package_name:
    description: 'name of the package to be published'
    required: true
  out:
    description: 'path to the `out` folder containing the compiled contracts'
    required: false
    default: 'out'
  interfaces:
    description: 'path to the interfaces directory'
    required: false
    default: 'solidity/interfaces'
  contracts:
    description: 'path to the contracts directory'
    required: false
    default: 'solidity/contracts'
  libraries:
    description: 'path to the libraries directory'
    required: false
    default: 'solidity/libraries'
  export_type:
    description: '`interface` for exporting only the interfaces and their ABIs, `contracts` for exporting the contracts, interfaces and their ABIs as well'
    required: false
    default: 'interfaces'

outputs:
  exported:
    description: 'boolean describing package was exported successfully or not'
runs:
  using: 'node20'
  main: 'dist/index.js'
